### ISSUE TITLE
What is Milestone 1?

### ISSUE THREAD

**Issue by watsonarw** [twlevelup/watch_edition_react#6]
In order to break down the work needed, I'd like to capture the key pieces of functionality that we need to replicate from the [existing watch app](https://github.com/twlevelup/watch_edition).

This should help us know when we're "done", at least to the point where we can comfortably use this as the base for student projects.

- [x] Create a repository
- [ ] ...
- [ ] Profit

## The app

- [ ] Clear separation of "framework" and "app", students should not need to touch anything in "framework", and only change/add things in "app".
- [ ] A generic "page" component that watch views extend from. Needs to provide an easy way of setting button actions

#### Home Page
- [x] LevelUp Logo
- [x] Clock
- [x] Some lorem ipsum text
- [ ] Top and bottom button for scrolling
- [ ] Some sort of notification?
- [ ] Right button to go to some lists. (At the moment it's a basic contact list)

#### Contact Page
- [x] A basic list component
- [ ] Top and bottom button to scroll the list
- [ ] Left button to go home

## Setup
- [ ] Fully automated ./go script. Not really a fan of `nvm` either
- [ ] Docker (yes / no ?)
- [ ] A list of recommended Atom / VS code packages
- [ ] Update README
- [ ] Update recommended readings

## Testing

- [ ] Code coverage report and thresholds that fail the build
- [ ] 100% coverage of "framework" code (or somehow exclude it from coverage reporting)
- [ ] Fast to run tests

## CI/CD

- [ ] Automated build/test/deploy pipeline
- [ ] Deployed static app (github pages, heroku serving static assets, or aws s3)

**Comment by raytung** [comment]
My thoughts are basically feature parity with existing app.

## The app 
#### Home Page
- [x] LevelUp Logo
- [x] Clock
- [x] Some lorem ipsum text
- [ ] Top and bottom button for scrolling
- [x] Some sort of notification?
- [x] Right button to go to some lists. (At the moment it's a basic contact list)

#### Contact Page
- [x] A basic list component
- [ ] Top and bottom button to scroll the list
- [x] Left button to go home

## Setup
- [ ] Fully automated ./go script. Not really a fan of `nvm` either
- [ ] Docker (yes / no ?)
- [ ] A list of recommended Atom / VS code packages
- [ ] Update README
- [ ] Update recommended readings

etc etc

**Comment by watsonarw** [comment]
I would add:

## The app

- [ ] Clear separation of "framework" and "app", students should not need to touch anything in "framework", and only change/add things in "app".
- [ ] A generic "page" component that watch views extend from. Needs to provide an easy way of setting button actions

## Testing

- [ ] Code coverage report and thresholds that fail the build
- [ ] 100% coverage of "framework" code (or somehow exclude it from coverage reporting)
- [ ] Fast to run tests

## CI/CD

- [ ] Automated build/test/deploy pipeline
- [ ] Deployed static app (github pages, heroku serving static assets, or aws s3)

**Comment by raytung** [comment]
Need to add a Wiki, as mentioned by Adam in https://github.com/twlevelup/watch_edition_react/issues/18

**Comment by sinan-aumarah** [comment]
Hi guys, since we are nearing the completion of Milestone 1. I just wanted to consolidate and confirm that the following is the final list for Milestone1? if you have any additions please just edit it.

## MVP 
#### Home Page
- [x] LevelUp Logo
- [x] Clock
- [x] Some lorem ipsum text
- [x] Top and bottom button for scrolling
- [x] Right button to go to some lists. (At the moment it's a basic contact list)

#### Contact Page
- [x] A basic list component
- [x] Top and bottom button to scroll the list
- [x] Left button to go home

#### Notification
- [x] Notifier form
- [x] Notification popup
- [ ] Notification popup configurable buttons ? is this milestone 1?

## Setup
- [x] Fully automated ./go script. Not really a fan of `nvm` either
- [ ] A list of recommended Atom / VS code packages
- [ ] CI to Slack integration
- [x] Update README
- [x] Update recommended readings
- [x] Update Wiki

## Testing
- [x] Code coverage report and thresholds that fail the build
- [x] 100% coverage of "framework" code (or somehow exclude it from coverage reporting)
- [x] Fast to run tests

## CI/CD
- [x] Automated build/test
- [ ] Automated deployment
  - [ ] Deployed static app (github pages, heroku serving static assets, or aws s3)

**Comment by alex-mitchem** [comment]
Do we actually need the Notification stuff?

**Comment by sinan-aumarah** [comment]
@AMitchemTW  I thought so! it was in the old app. If we don't need it's better, less code :)

**Comment by adamhope** [comment]
Yes. It gets used a lot

**Comment by adamhope** [comment]
It's a way of simulating server based functionality. It's mostly used for push notifications like "your next class is about to start in room …", "your friend is in the area" etc etc

**Comment by alex-mitchem** [comment]
So notifications can be generated by the watch pages, or only by manually typing them?
